# Generated by Django 3.0.4 on 2020-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0003_auto_20200530_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='job',
        ),
        migrations.RemoveField(
            model_name='module',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='modules',
            field=models.ManyToManyField(to='qcareers.Module'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='qcareers.Skill'),
        ),
    ]
