# Generated by Django 3.0.4 on 2020-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0004_auto_20200530_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(to='qcareers.Skill'),
        ),
    ]
