# Generated by Django 3.0.6 on 2020-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0005_module_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
