# Generated by Django 3.0.6 on 2020-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0007_skill_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
