# Generated by Django 3.0.6 on 2020-06-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0008_job_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='modules',
        ),
    ]
