# Generated by Django 3.0.6 on 2020-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0010_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='job_role',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
