# Generated by Django 3.0.6 on 2020-06-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0011_recommendation_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='job_role',
        ),
    ]
