# Generated by Django 3.0.6 on 2020-06-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0014_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recOne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recThree',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recTwo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
