# Generated by Django 3.0.6 on 2020-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0015_auto_20200602_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='job_recommendations',
        ),
    ]
