# Generated by Django 3.0.6 on 2020-06-01 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0016_remove_recommendation_job_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
