# Generated by Django 3.0.6 on 2020-06-01 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0018_auto_20200602_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='dateAndTimeOfRec',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
