# Generated by Django 3.0.6 on 2020-06-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcareers', '0019_auto_20200602_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250, null=True)),
                ('lastName', models.CharField(max_length=250, null=True)),
                ('message', models.CharField(max_length=250, null=True)),
                ('dateAdminRequested', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
