# Generated by Django 3.0.6 on 2020-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0025_auto_20200604_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='grade',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
    ]
