# Generated by Django 3.0.6 on 2020-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0026_module_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
