# Generated by Django 3.0.6 on 2020-06-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcareers', '0027_auto_20200606_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
